apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    app.kubernetes.io/component: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.27.0
  name: jaeger
  namespace: default
spec:
  agent:
    strategy: DaemonSet
  storage:
    options:
      es:
        num-replicas: 0
        num-shards: 1
        server-urls: https://elastic-jaeger-es-http:9200
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret
    type: elasticsearch
  strategy: production
  volumeMounts:
  - mountPath: /es/certificates/
    name: certificates
    readOnly: true
  volumes:
  - name: certificates
    secret:
      secretName: elastic-jaeger-es-http-certs-public
