apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.8.0
    control-plane: elastic-operator
  name: elastic-webhook-server-cert
  namespace: default
