apiVersion: v1
data:
  eck.yaml: |
    log-verbosity: 0
    metrics-port: 0
    container-registry: docker.elastic.co
    max-concurrent-reconciles: 3
    ca-cert-validity: 8760h
    ca-cert-rotate-before: 24h
    cert-validity: 8760h
    cert-rotate-before: 24h
    set-default-security-context: true
    kube-client-timeout: 60s
    elasticsearch-client-timeout: 180s
    disable-telemetry: false
    validate-storage-class: true
    enable-webhook: true
    webhook-name: elastic-webhook.k8s.elastic.co
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.8.0
    control-plane: elastic-operator
  name: elastic-operator
  namespace: default
